Repository DevTillDie/ForestTori, pull requests merged in 2024-05, with the labels that each got.

#64 design: edit font style
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Source/Utils/Extension/String+.swift
  ForestTori/ForestTori/Source/View/Garden/HistoryDetailView.swift
  ForestTori/ForestTori/Source/View/Main/History/WriteHistoryView.swift
  ForestTori/ForestTori/Source/View/Main/PlantCardView.swift
  ForestTori/ForestTori/Source/View/Main/PlantView.swift
Labels: 🎨 design

#65 feat: add the ability to reselect photos
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForestTori/ForestTori/Source/View/Main/History/WriteHistoryView.swift
Labels: 🎨 design, 🛠️ chore

#66 design : add screen transition animations
  ForestTori/ForestTori/Source/View/Main/MainView.swift
  ForestTori/ForestTori/Source/View/Main/PlantView.swift
  ForestTori/ForestTori/Source/View/Onboarding/OnboardingCompletionView.swift
  ForestTori/ForestTori/Source/View/ServieStateView.swift
  ForestTori/ForestTori/Source/ViewModel/ServiceStateViewModel.swift
Labels: 🎨 design

#71 chore: pass user nickname to main dialogue text
  ForestTori/ForestTori/Source/ViewModel/EpilogueViewModel.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
  ForestTori/ForestTori/Source/ViewModel/OnboardingViewModel.swift
Labels: 🛠️ chore

#72 feat: fix error
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Resource/Chapters/SpringPlants.tsv
  ForestTori/ForestTori/Source/Utils/Manager/DataManager.swift
  ForestTori/ForestTori/Source/View/Garden/GardenView.swift
  ForestTori/ForestTori/Source/View/Garden/HistoryDetailView.swift
  ForestTori/ForestTori/Source/View/Garden/HistoryView.swift
  ForestTori/ForestTori/Source/View/Main/MainView.swift
  ForestTori/ForestTori/Source/View/Main/PlantCardView.swift
  ForestTori/ForestTori/Source/View/Main/PlantPotView.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
Labels: 🐛 fix

#73 fix: add persistence for main
  ForestTori/ForestTori.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForestTori/ForestTori/Source/Utils/Manager/GameManager.swift
  ForestTori/ForestTori/Source/View/Garden/GardenView.swift
  ForestTori/ForestTori/Source/View/Main/MainView.swift
  ForestTori/ForestTori/Source/View/Main/PlantView.swift
  ForestTori/ForestTori/Source/View/ServieStateView.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
  ForestTori/ForestTori/Source/ViewModel/ServiceStateViewModel.swift
Labels: 🐛 fix, ♻️ Refactor

#77 chore: resize frame size for garden scene
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Source/Utils/Component/Scenes/GardenScene.swift
  ForestTori/ForestTori/Source/View/Garden/GardenARView.swift
  ForestTori/ForestTori/Source/View/Main/PlantPotView.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
Labels: 🐛 fix, ♻️ Refactor, 🛠️ chore

#79 chore: update deployment setting
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Source/Utils/Component/BottomSheet.swift
  ForestTori/ForestTori/Source/Utils/Component/ProgressStyle.swift
  ForestTori/ForestTori/Source/Utils/Extension/String+.swift
  ForestTori/ForestTori/Source/Utils/Extension/View+.swift
  ForestTori/ForestTori/Source/Utils/Manager/GameManager.swift
  ForestTori/ForestTori/Source/Utils/Modifier/ModifierInitFile.swift
  ForestTori/ForestTori/Source/Utils/Modifier/RoundedCorners.swift
  ForestTori/ForestTori/Source/View/Garden/HistoryDetailView.swift
  ForestTori/ForestTori/Source/View/Garden/HistoryView.swift
  ForestTori/ForestTori/Source/View/Main/History/WriteHistoryView.swift
  ForestTori/ForestTori/Source/View/Main/MainView.swift
  ForestTori/ForestTori/Source/View/Main/PlantCardView.swift
  ForestTori/ForestTori/Source/View/Main/PlantView.swift
  ForestTori/ForestTori/Source/View/Onboarding/NameSettingView.swift
  ForestTori/ForestTori/Source/View/Onboarding/OnboardingNamingView.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
  ForestTori/ForestTori/Source/ViewModel/ServiceStateViewModel.swift
Labels: 🐛 fix, ♻️ Refactor, 🛠️ chore

#84 file: modify files
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Resource/3D_Objects/3D_Plants/Cottontree/Cottontree1.dae
  ForestTori/ForestTori/Resource/3D_Objects/3D_Plants/Cottontree/Cottontree1.scn
  ForestTori/ForestTori/Resource/3D_Objects/3D_Plants/Cottontree/Cottontree2.dae
  ForestTori/ForestTori/Resource/3D_Objects/3D_Plants/Cottontree/Cottontree2.scn
  ForestTori/ForestTori/Resource/3D_Objects/3D_Plants/Cottontree/Cottontree3.dae
  ForestTori/ForestTori/Resource/3D_Objects/3D_Plants/Cottontree/Cottontree3.scn
  ForestTori/ForestTori/Resource/Chapters/AutumnPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/Chapters.tsv
  ForestTori/ForestTori/Resource/Chapters/SpringPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/SummerPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/WinterPlants.tsv
Labels: 🐛 fix

#86 fix to ending logic
  ForestTori/ForestTori/Source/Utils/Manager/GameManager.swift
  ForestTori/ForestTori/Source/View/Garden/GardenView.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
  ForestTori/ForestTori/Source/ViewModel/ServiceStateViewModel.swift
Labels: 🚨 Hotfix

#87 fix : fix errors
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForestTori/ForestTori/Resource/CharacterDialogues/SummerCharacter.tsv
  ForestTori/ForestTori/Resource/CharacterDialogues/WinterCharacter.tsv
  ForestTori/ForestTori/Source/Utils/Component/BottomSheet.swift
  ForestTori/ForestTori/Source/Utils/Component/UnevenRoundedRectangle.swift
  ForestTori/ForestTori/Source/Utils/Modifier/RoundedCorners.swift
  ForestTori/ForestTori/Source/View/Main/PlantPotView.swift
  ForestTori/ForestTori/Source/ViewModel/HistoryViewModel.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
Labels: 🐛 fix

#89 fix: fix errors
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Source/Ending/EpilogueView.swift
  ForestTori/ForestTori/Source/ViewModel/EpilogueViewModel.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
Labels: 🚨 Hotfix
