Repository DevTillDie/ForestTori, pull requests merged in 2024-02, with the labels that each got.

#8 feat: add game manager
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Source/Model/GameManager.swift
Labels: ✨ feature

#12 add: add design system
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/BeigePrimary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/BeigeSecondary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/BeigeTertiary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/Black.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/BluePrimary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/BrownPrimary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/BrownSecondary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/BrownTertiary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/Gray10.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/Gray20.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/Gray30.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/Gray40.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/Gray50.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/GreenPrimary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/GreenSecondary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/GreenTertiary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/MintPrimary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/RedPrimary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/RedSecondary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/White.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/YellowPrimary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/YellowSecondary.colorset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Colors/YellowTertiary.colorset/Contents.json
  ForestTori/ForestTori/Source/Utils/Extension/Font+.swift
  ForestTori/ForestTori/Source/Utils/Extension/InitFile.swift
Labels: ➕ add

#17 file: add font resources
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Resource/Pretendard/Pretendard-Bold.ttf
  ForestTori/ForestTori/Resource/Pretendard/Pretendard-Light.ttf
  ForestTori/ForestTori/Resource/Pretendard/Pretendard-Regular.ttf
  ForestTori/ForestTori/Resource/Pretendard/Pretendard-SemiBold.ttf
Labels: 📁 file

#18 design: create MainView UI
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Source/Utils/Extension/View+.swift
  ForestTori/ForestTori/Source/View/Main/MainView.swift
  ForestTori/ForestTori/Source/View/Main/PlantPotView.swift
  ForestTori/ForestTori/Source/View/Main/PlantView.swift
Labels: 🎨 design

#20 feat: read dialogue files
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/.swiftlint.yml
  ForestTori/ForestTori/Resource/CharacterDialogues/AutumnCharacter.csv
  ForestTori/ForestTori/Resource/CharacterDialogues/AutumnCharacter.tsv
  ForestTori/ForestTori/Resource/CharacterDialogues/SpringCharacter.csv
  ForestTori/ForestTori/Resource/CharacterDialogues/SpringCharacter.tsv
  ForestTori/ForestTori/Resource/CharacterDialogues/SummerCharacter.csv
  ForestTori/ForestTori/Resource/CharacterDialogues/SummerCharacter.tsv
  ForestTori/ForestTori/Resource/CharacterDialogues/WinterCharacter.csv
  ForestTori/ForestTori/Resource/CharacterDialogues/WinterCharacter.tsv
  ForestTori/ForestTori/Source/Model/Dialogue.swift
  ForestTori/ForestTori/Source/Utils/Component/ComponentInitFile.swift
  ForestTori/ForestTori/Source/Utils/Modifier/InitFile.swift
  ForestTori/ForestTori/Source/Utils/Modifier/ModifierInitFile.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
Labels: ✨ feature

#25 feat: create select plant carousel view
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForestTori/ForestTori/Source/Model/DataManager.swift
  ForestTori/ForestTori/Source/Model/GameManager.swift
  ForestTori/ForestTori/Source/Model/Plant.swift
  ForestTori/ForestTori/Source/View/Main/MainView.swift
  ForestTori/ForestTori/Source/View/Main/PlantCardView.swift
  ForestTori/ForestTori/Source/View/Main/PlantView.swift
  ForestTori/ForestTori/Source/View/Main/SelectPlantView.swift
Labels: ✨ feature, 🎨 design

#27 design: create garden view
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Source/View/Garden/GardenView.swift
Labels: 🎨 design
