Repository DevTillDie/ForestTori, pull requests merged in 2024-04, with the labels that each got.

#38 feat: set initial data in DataManger
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Resource/Chapters/AutumnPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/Chapters.tsv
  ForestTori/ForestTori/Resource/Chapters/SpringPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/SummerPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/WinterPlants.tsv
  ForestTori/ForestTori/Source/Model/Chapter.swift
  ForestTori/ForestTori/Source/Model/Mission.swift
  ForestTori/ForestTori/Source/Model/Plant.swift
  ForestTori/ForestTori/Source/Utils/Manager/DataManager.swift
Labels: ✨ feature

#43 feat: show garden object
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForestTori/ForestTori/Source/Utils/Component/Scenes/GardenScene.swift
  ForestTori/ForestTori/Source/View/Garden/GardenView.swift
Labels: ✨ feature

#47 feat: add ar view
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Source/Utils/Component/Scenes/GardenScene.swift
  ForestTori/ForestTori/Source/View/Garden/CameraPreview.swift
  ForestTori/ForestTori/Source/View/Garden/GardenARView.swift
  ForestTori/ForestTori/Source/View/Garden/GardenView.swift
  ForestTori/ForestTori/Source/ViewModel/GardenARViewModel.swift
  ForestTori/ForestTori/Source/ViewModel/OnboardingViewModel.swift
Labels: ✨ feature

#48 feat : add plant history view
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForestTori/ForestTori/Source/Model/History.swift
  ForestTori/ForestTori/Source/Utils/Manager/RealmManager.swift
  ForestTori/ForestTori/Source/View/Main/History/HistoryView.swift
  ForestTori/ForestTori/Source/View/Main/History/ImagePicker.swift
  ForestTori/ForestTori/Source/ViewModel/HistoryViewModel.swift
Labels: ✨ feature, 🎨 design

#52 chore: edit History Model
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Source/Model/History.swift
  ForestTori/ForestTori/Source/Utils/Extension/Date+.swift
  ForestTori/ForestTori/Source/Utils/Manager/RealmManager.swift
  ForestTori/ForestTori/Source/View/Main/History/HistoryView.swift
  ForestTori/ForestTori/Source/ViewModel/HistoryViewModel.swift
Labels: 🛠️ chore

#50 feat :add HistoryView to MainView
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Source/Utils/KeyboardHandler.swift
  ForestTori/ForestTori/Source/View/Main/History/HistoryView.swift
  ForestTori/ForestTori/Source/View/Main/History/ImagePicker.swift
  ForestTori/ForestTori/Source/View/Main/MainView.swift
  ForestTori/ForestTori/Source/View/Main/PlantView.swift
  ForestTori/ForestTori/Source/ViewModel/HistoryViewModel.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
Labels: ✨ feature

#53 feat: add navigation between main view and garden view
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Resource/Chapters/AutumnPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/SpringPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/SummerPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/WinterPlants.tsv
  ForestTori/ForestTori/Source/Model/Plant.swift
  ForestTori/ForestTori/Source/Model/User.swift
  ForestTori/ForestTori/Source/Utils/Component/Scenes/GardenScene.swift
  ForestTori/ForestTori/Source/Utils/Manager/DataManager.swift
  ForestTori/ForestTori/Source/Utils/Manager/GameManager.swift
  ForestTori/ForestTori/Source/View/Garden/GardenView.swift
  ForestTori/ForestTori/Source/View/Main/CompleteMissionView.swift
  ForestTori/ForestTori/Source/View/Main/MainView.swift
Labels: ✨ feature, 🎨 design

#57 feat : create HistoryView in GardenView
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/PlantSelect/PlantSelect_Autumn/maple.imageset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/PlantSelect/PlantSelect_Autumn/maple.imageset/STR_Img_PlantSelect_Autumn_1.png
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/PlantSelect/PlantSelect_Spring/dandelion.imageset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/PlantSelect/PlantSelect_Spring/dandelion.imageset/STR_Img_PlantSelect_Spring_1.png
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/PlantSelect/PlantSelect_Summer/cactus.imageset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/PlantSelect/PlantSelect_Summer/cactus.imageset/STR_Img_PlantSelect_Summer_1.png
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/PlantSelect/PlantSelect_Winter/cottontree.imageset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/PlantSelect/PlantSelect_Winter/cottontree.imageset/STR_Img_PlantSelect_winter_1.png
  ForestTori/ForestTori/Resource/Chapters/AutumnPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/SpringPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/SummerPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/WinterPlants.tsv
  ForestTori/ForestTori/Source/Utils/Component/BottomSheet.swift
  ForestTori/ForestTori/Source/Utils/Component/Scenes/GardenScene.swift
  ForestTori/ForestTori/Source/Utils/Manager/RealmManager.swift
  ForestTori/ForestTori/Source/View/Garden/GardenARView.swift
  ForestTori/ForestTori/Source/View/Garden/GardenView.swift
  ForestTori/ForestTori/Source/View/Garden/HistoryDetailView.swift
  ForestTori/ForestTori/Source/View/Garden/HistoryView.swift
  ForestTori/ForestTori/Source/View/Main/History/ImagePicker.swift
  ForestTori/ForestTori/Source/View/Main/History/WriteHistoryView.swift
  ForestTori/ForestTori/Source/View/Main/MainView.swift
  ForestTori/ForestTori/Source/ViewModel/HistoryViewModel.swift
  ForestTori/ForestTori/Source/ViewModel/WriteHistoryViewModel.swift
Labels: ✨ feature, 🎨 design

#59 chore: add start new game function
  ForestTori/ForestTori/Source/Ending/EndingView.swift
  ForestTori/ForestTori/Source/Ending/EpilogueView.swift
  ForestTori/ForestTori/Source/Utils/Manager/GameManager.swift
  ForestTori/ForestTori/Source/View/Garden/GardenARView.swift
  ForestTori/ForestTori/Source/View/Garden/GardenView.swift
  ForestTori/ForestTori/Source/View/Main/CompleteMissionView.swift
  ForestTori/ForestTori/Source/View/Main/MainView.swift
  ForestTori/ForestTori/Source/View/Main/PlantView.swift
  ForestTori/ForestTori/Source/View/Main/SelectPlantView.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
Labels: 🛠️ chore
