Repository DevTillDie/ForestTori, pull requests merged in 2024-08, with the labels that each got.

#94 design: modify history view ui
  ForestTori/ForestTori/Source/View/Garden/GardenView.swift
  ForestTori/ForestTori/Source/View/Garden/HistoryDetailView.swift
  ForestTori/ForestTori/Source/View/Garden/HistoryView.swift
  ForestTori/ForestTori/Source/View/Main/History/WriteHistoryView.swift
  ForestTori/ForestTori/Source/View/Main/MainView.swift
Labels: 🎨 design

#100 refactor : modify DataManager
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForestTori/ForestTori/Source/Model/Plant.swift
  ForestTori/ForestTori/Source/Utils/Manager/DataManager.swift
  ForestTori/ForestTori/Source/Utils/Manager/GameManager.swift
  ForestTori/ForestTori/Source/View/Main/MainView.swift
Labels: ♻️ Refactor

#101 feat: add photo edit function
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Source/Utils/Extension/View+.swift
  ForestTori/ForestTori/Source/View/Main/History/ImageCropView.swift
  ForestTori/ForestTori/Source/View/Main/History/ImagePicker.swift
  ForestTori/ForestTori/Source/View/Main/History/WriteHistoryView.swift
Labels: ✨ feature

#103 feat: add info button for cotton tree
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/Buttons/InfoButton.imageset/Button_Message.png
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/Buttons/InfoButton.imageset/Button_Message@2x.png
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/Buttons/InfoButton.imageset/Button_Message@3x.png
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/Buttons/InfoButton.imageset/Contents.json
  ForestTori/ForestTori/Resource/Assets.xcassets/Images/Buttons/InfoButton.imageset/STR_Img_asset_button_info.png
  ForestTori/ForestTori/Source/View/Main/PlantView.swift
  ForestTori/ForestTori/Source/ViewModel/MainViewModel.swift
Labels: ✨ feature, 🎨 design

#107 file: edit chapter files
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori/Resource/Chapters/AutumnPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/Chapters.tsv
  ForestTori/ForestTori/Resource/Chapters/SpringPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/SummerPlants.tsv
  ForestTori/ForestTori/Resource/Chapters/WinterPlants.tsv
Labels: 📁 file

#109 fix: fix image crop view error
  ForestTori/ForestTori/Source/View/Main/History/WriteHistoryView.swift
Labels: 🐛 fix
