Repository DevTillDie/ForestTori, pull requests merged in 2024-03, with the labels that each got.

#30 feat: add ending process
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForestTori/ForestTori/Info.plist
  ForestTori/ForestTori/Source/EndingView.swift
  ForestTori/ForestTori/Source/View/Onboarding/OnboardingNamingView.swift
  ForestTori/ForestTori/Source/ViewModel/EndingViewModel.swift
  ForestTori/ForestTori/Source/ViewModel/OnboardingViewModel.swift
Labels: ✨ feature

#33 docs: modify the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📑 docs

#34 file: move to manager folder
  ForestTori/ForestTori.xcodeproj/project.pbxproj
  ForestTori/ForestTori.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForestTori/ForestTori/Source/Utils/Manager/DataManager.swift
  ForestTori/ForestTori/Source/Utils/Manager/GameManager.swift
Labels: 📁 file
